export enum Role {
  ADMIN = 'ADMIN',
  CUSTOMER = 'CUSTOMER',
  RECEPTIONIST = 'RECEPTIONIST', 
  HOUSEKEEPING = 'HOUSEKEEPING', 
  MAINTENANCE = 'MAINTENANCE', 
  SECURITY = 'SECURITY', 
  WAITER = 'WAITER', 
  CHEF = 'CHEF', 
  POS_SERVICE = 'POS_SERVICE',
}